//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLVApplication.LibService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", ConfigurationName="LibService.MLVLibService")]
    public interface MLVLibService {
        
        // CODEGEN: Parameter 'getCategoriesReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCategoriesReturn")]
        MLVApplication.LibService.getCategoriesResponse getCategories(MLVApplication.LibService.getCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getCategoriesResponse> getCategoriesAsync(MLVApplication.LibService.getCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getImageReturn")]
        string getImage(int idBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getImageReturn")]
        System.Threading.Tasks.Task<string> getImageAsync(int idBook);
        
        // CODEGEN: Parameter 'getRangeReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRangeReturn")]
        MLVApplication.LibService.getRangeResponse getRange(MLVApplication.LibService.getRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getRangeResponse> getRangeAsync(MLVApplication.LibService.getRangeRequest request);
        
        // CODEGEN: Parameter 'getBooksForSellReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBooksForSellReturn")]
        MLVApplication.LibService.getBooksForSellResponse getBooksForSell(MLVApplication.LibService.getBooksForSellRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getBooksForSellResponse> getBooksForSellAsync(MLVApplication.LibService.getBooksForSellRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTotalBooksReturn")]
        int getTotalBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTotalBooksReturn")]
        System.Threading.Tasks.Task<int> getTotalBooksAsync();
        
        // CODEGEN: Parameter 'searchBooksReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchBooksReturn")]
        MLVApplication.LibService.searchBooksResponse searchBooks(MLVApplication.LibService.searchBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.searchBooksResponse> searchBooksAsync(MLVApplication.LibService.searchBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sellBookReturn")]
        bool sellBook(long cardID, string secret, string devise, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sellBookReturn")]
        System.Threading.Tasks.Task<bool> sellBookAsync(long cardID, string secret, string devise, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getMostConsultedBookReturn")]
        MLVApplication.LibService.BookPOJO getMostConsultedBook(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getMostConsultedBookReturn")]
        System.Threading.Tasks.Task<MLVApplication.LibService.BookPOJO> getMostConsultedBookAsync(int number);
        
        // CODEGEN: Parameter 'getMostConsultedBookFormattedReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getMostConsultedBookFormattedReturn")]
        MLVApplication.LibService.getMostConsultedBookFormattedResponse getMostConsultedBookFormatted(MLVApplication.LibService.getMostConsultedBookFormattedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getMostConsultedBookFormattedResponse> getMostConsultedBookFormattedAsync(MLVApplication.LibService.getMostConsultedBookFormattedRequest request);
        
        // CODEGEN: Parameter 'getMostSimilarBookReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getMostSimilarBookReturn")]
        MLVApplication.LibService.getMostSimilarBookResponse getMostSimilarBook(MLVApplication.LibService.getMostSimilarBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getMostSimilarBookResponse> getMostSimilarBookAsync(MLVApplication.LibService.getMostSimilarBookRequest request);
        
        // CODEGEN: Parameter 'searchFormattedBooksReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="searchFormattedBooksReturn")]
        MLVApplication.LibService.searchFormattedBooksResponse searchFormattedBooks(MLVApplication.LibService.searchFormattedBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.searchFormattedBooksResponse> searchFormattedBooksAsync(MLVApplication.LibService.searchFormattedBooksRequest request);
        
        // CODEGEN: Parameter 'getBookFromCategoryReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBookFromCategoryReturn")]
        MLVApplication.LibService.getBookFromCategoryResponse getBookFromCategory(MLVApplication.LibService.getBookFromCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getBookFromCategoryResponse> getBookFromCategoryAsync(MLVApplication.LibService.getBookFromCategoryRequest request);
        
        // CODEGEN: Parameter 'getFormattedBookFromCategoryReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFormattedBookFromCategoryReturn")]
        MLVApplication.LibService.getFormattedBookFromCategoryResponse getFormattedBookFromCategory(MLVApplication.LibService.getFormattedBookFromCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedBookFromCategoryResponse> getFormattedBookFromCategoryAsync(MLVApplication.LibService.getFormattedBookFromCategoryRequest request);
        
        // CODEGEN: Parameter 'getFormattedBooksReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFormattedBooksReturn")]
        MLVApplication.LibService.getFormattedBooksResponse getFormattedBooks(MLVApplication.LibService.getFormattedBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedBooksResponse> getFormattedBooksAsync(MLVApplication.LibService.getFormattedBooksRequest request);
        
        // CODEGEN: Parameter 'getFormattedRangeReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFormattedRangeReturn")]
        MLVApplication.LibService.getFormattedRangeResponse getFormattedRange(MLVApplication.LibService.getFormattedRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedRangeResponse> getFormattedRangeAsync(MLVApplication.LibService.getFormattedRangeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategories", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getCategoriesRequest {
        
        public getCategoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategoriesResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getCategoriesReturn")]
        public string[] getCategoriesReturn;
        
        public getCategoriesResponse() {
        }
        
        public getCategoriesResponse(string[] getCategoriesReturn) {
            this.getCategoriesReturn = getCategoriesReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://models.bilmancamp.rmirest.upem.fr")]
    public partial class BookPOJO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] authorsField;
        
        private string[] categoriesField;
        
        private CommentImpl[] commentsField;
        
        private int consultationNumberField;
        
        private int idField;
        
        private string mainImageField;
        
        private double priceField;
        
        private int rateNumberField;
        
        private string[] secondaryImagesField;
        
        private string summaryField;
        
        private string[] tagsField;
        
        private string titleField;
        
        private float totalRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.bilmancamp.rmirest.upem.fr", IsNullable=false)]
        public string[] authors {
            get {
                return this.authorsField;
            }
            set {
                this.authorsField = value;
                this.RaisePropertyChanged("authors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.bilmancamp.rmirest.upem.fr", IsNullable=false)]
        public string[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.bilmancamp.rmirest.upem.fr", IsNullable=false)]
        public CommentImpl[] comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int consultationNumber {
            get {
                return this.consultationNumberField;
            }
            set {
                this.consultationNumberField = value;
                this.RaisePropertyChanged("consultationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string mainImage {
            get {
                return this.mainImageField;
            }
            set {
                this.mainImageField = value;
                this.RaisePropertyChanged("mainImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int rateNumber {
            get {
                return this.rateNumberField;
            }
            set {
                this.rateNumberField = value;
                this.RaisePropertyChanged("rateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.bilmancamp.rmirest.upem.fr", IsNullable=false)]
        public string[] secondaryImages {
            get {
                return this.secondaryImagesField;
            }
            set {
                this.secondaryImagesField = value;
                this.RaisePropertyChanged("secondaryImages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://ws.bilmancamp.rmirest.upem.fr", IsNullable=false)]
        public string[] tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("tags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public float totalRate {
            get {
                return this.totalRateField;
            }
            set {
                this.totalRateField = value;
                this.RaisePropertyChanged("totalRate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://models.bilmancamp.rmirest.upem.fr")]
    public partial class CommentImpl : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRange", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public int offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=1)]
        public int limit;
        
        public getRangeRequest() {
        }
        
        public getRangeRequest(int offset, int limit) {
            this.offset = offset;
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRangeResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getRangeReturn")]
        public MLVApplication.LibService.BookPOJO[] getRangeReturn;
        
        public getRangeResponse() {
        }
        
        public getRangeResponse(MLVApplication.LibService.BookPOJO[] getRangeReturn) {
            this.getRangeReturn = getRangeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBooksForSell", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getBooksForSellRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public int limit;
        
        public getBooksForSellRequest() {
        }
        
        public getBooksForSellRequest(int limit) {
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBooksForSellResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getBooksForSellResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getBooksForSellReturn")]
        public MLVApplication.LibService.BookPOJO[] getBooksForSellReturn;
        
        public getBooksForSellResponse() {
        }
        
        public getBooksForSellResponse(MLVApplication.LibService.BookPOJO[] getBooksForSellReturn) {
            this.getBooksForSellReturn = getBooksForSellReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchBooks", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class searchBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("tags")]
        public string[] tags;
        
        public searchBooksRequest() {
        }
        
        public searchBooksRequest(string[] tags) {
            this.tags = tags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchBooksResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class searchBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("searchBooksReturn")]
        public MLVApplication.LibService.BookPOJO[] searchBooksReturn;
        
        public searchBooksResponse() {
        }
        
        public searchBooksResponse(MLVApplication.LibService.BookPOJO[] searchBooksReturn) {
            this.searchBooksReturn = searchBooksReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMostConsultedBookFormatted", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getMostConsultedBookFormattedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public int number;
        
        public getMostConsultedBookFormattedRequest() {
        }
        
        public getMostConsultedBookFormattedRequest(int number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMostConsultedBookFormattedResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getMostConsultedBookFormattedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getMostConsultedBookFormattedReturn")]
        public string[] getMostConsultedBookFormattedReturn;
        
        public getMostConsultedBookFormattedResponse() {
        }
        
        public getMostConsultedBookFormattedResponse(string[] getMostConsultedBookFormattedReturn) {
            this.getMostConsultedBookFormattedReturn = getMostConsultedBookFormattedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMostSimilarBook", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getMostSimilarBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public MLVApplication.LibService.BookPOJO model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=1)]
        public int number;
        
        public getMostSimilarBookRequest() {
        }
        
        public getMostSimilarBookRequest(MLVApplication.LibService.BookPOJO model, int number) {
            this.model = model;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMostSimilarBookResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getMostSimilarBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getMostSimilarBookReturn")]
        public MLVApplication.LibService.BookPOJO[] getMostSimilarBookReturn;
        
        public getMostSimilarBookResponse() {
        }
        
        public getMostSimilarBookResponse(MLVApplication.LibService.BookPOJO[] getMostSimilarBookReturn) {
            this.getMostSimilarBookReturn = getMostSimilarBookReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFormattedBooks", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class searchFormattedBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("tags")]
        public string[] tags;
        
        public searchFormattedBooksRequest() {
        }
        
        public searchFormattedBooksRequest(string[] tags) {
            this.tags = tags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFormattedBooksResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class searchFormattedBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("searchFormattedBooksReturn")]
        public string[] searchFormattedBooksReturn;
        
        public searchFormattedBooksResponse() {
        }
        
        public searchFormattedBooksResponse(string[] searchFormattedBooksReturn) {
            this.searchFormattedBooksReturn = searchFormattedBooksReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBookFromCategory", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getBookFromCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public string category;
        
        public getBookFromCategoryRequest() {
        }
        
        public getBookFromCategoryRequest(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBookFromCategoryResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getBookFromCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getBookFromCategoryReturn")]
        public MLVApplication.LibService.BookPOJO[] getBookFromCategoryReturn;
        
        public getBookFromCategoryResponse() {
        }
        
        public getBookFromCategoryResponse(MLVApplication.LibService.BookPOJO[] getBookFromCategoryReturn) {
            this.getBookFromCategoryReturn = getBookFromCategoryReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFormattedBookFromCategory", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getFormattedBookFromCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public string category;
        
        public getFormattedBookFromCategoryRequest() {
        }
        
        public getFormattedBookFromCategoryRequest(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFormattedBookFromCategoryResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getFormattedBookFromCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getFormattedBookFromCategoryReturn")]
        public string[] getFormattedBookFromCategoryReturn;
        
        public getFormattedBookFromCategoryResponse() {
        }
        
        public getFormattedBookFromCategoryResponse(string[] getFormattedBookFromCategoryReturn) {
            this.getFormattedBookFromCategoryReturn = getFormattedBookFromCategoryReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFormattedBooks", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getFormattedBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public int limit;
        
        public getFormattedBooksRequest() {
        }
        
        public getFormattedBooksRequest(int limit) {
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFormattedBooksResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getFormattedBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getFormattedBooksReturn")]
        public string[] getFormattedBooksReturn;
        
        public getFormattedBooksResponse() {
        }
        
        public getFormattedBooksResponse(string[] getFormattedBooksReturn) {
            this.getFormattedBooksReturn = getFormattedBooksReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFormattedRange", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getFormattedRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        public int offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=1)]
        public int limit;
        
        public getFormattedRangeRequest() {
        }
        
        public getFormattedRangeRequest(int offset, int limit) {
            this.offset = offset;
            this.limit = limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFormattedRangeResponse", WrapperNamespace="http://ws.bilmancamp.rmirest.upem.fr", IsWrapped=true)]
    public partial class getFormattedRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bilmancamp.rmirest.upem.fr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getFormattedRangeReturn")]
        public string[] getFormattedRangeReturn;
        
        public getFormattedRangeResponse() {
        }
        
        public getFormattedRangeResponse(string[] getFormattedRangeReturn) {
            this.getFormattedRangeReturn = getFormattedRangeReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MLVLibServiceChannel : MLVApplication.LibService.MLVLibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MLVLibServiceClient : System.ServiceModel.ClientBase<MLVApplication.LibService.MLVLibService>, MLVApplication.LibService.MLVLibService {
        
        public MLVLibServiceClient() {
        }
        
        public MLVLibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MLVLibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MLVLibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MLVLibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getCategoriesResponse MLVApplication.LibService.MLVLibService.getCategories(MLVApplication.LibService.getCategoriesRequest request) {
            return base.Channel.getCategories(request);
        }
        
        public string[] getCategories() {
            MLVApplication.LibService.getCategoriesRequest inValue = new MLVApplication.LibService.getCategoriesRequest();
            MLVApplication.LibService.getCategoriesResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getCategories(inValue);
            return retVal.getCategoriesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getCategoriesResponse> MLVApplication.LibService.MLVLibService.getCategoriesAsync(MLVApplication.LibService.getCategoriesRequest request) {
            return base.Channel.getCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getCategoriesResponse> getCategoriesAsync() {
            MLVApplication.LibService.getCategoriesRequest inValue = new MLVApplication.LibService.getCategoriesRequest();
            return ((MLVApplication.LibService.MLVLibService)(this)).getCategoriesAsync(inValue);
        }
        
        public string getImage(int idBook) {
            return base.Channel.getImage(idBook);
        }
        
        public System.Threading.Tasks.Task<string> getImageAsync(int idBook) {
            return base.Channel.getImageAsync(idBook);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getRangeResponse MLVApplication.LibService.MLVLibService.getRange(MLVApplication.LibService.getRangeRequest request) {
            return base.Channel.getRange(request);
        }
        
        public MLVApplication.LibService.BookPOJO[] getRange(int offset, int limit) {
            MLVApplication.LibService.getRangeRequest inValue = new MLVApplication.LibService.getRangeRequest();
            inValue.offset = offset;
            inValue.limit = limit;
            MLVApplication.LibService.getRangeResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getRange(inValue);
            return retVal.getRangeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getRangeResponse> MLVApplication.LibService.MLVLibService.getRangeAsync(MLVApplication.LibService.getRangeRequest request) {
            return base.Channel.getRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getRangeResponse> getRangeAsync(int offset, int limit) {
            MLVApplication.LibService.getRangeRequest inValue = new MLVApplication.LibService.getRangeRequest();
            inValue.offset = offset;
            inValue.limit = limit;
            return ((MLVApplication.LibService.MLVLibService)(this)).getRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getBooksForSellResponse MLVApplication.LibService.MLVLibService.getBooksForSell(MLVApplication.LibService.getBooksForSellRequest request) {
            return base.Channel.getBooksForSell(request);
        }
        
        public MLVApplication.LibService.BookPOJO[] getBooksForSell(int limit) {
            MLVApplication.LibService.getBooksForSellRequest inValue = new MLVApplication.LibService.getBooksForSellRequest();
            inValue.limit = limit;
            MLVApplication.LibService.getBooksForSellResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getBooksForSell(inValue);
            return retVal.getBooksForSellReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getBooksForSellResponse> MLVApplication.LibService.MLVLibService.getBooksForSellAsync(MLVApplication.LibService.getBooksForSellRequest request) {
            return base.Channel.getBooksForSellAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getBooksForSellResponse> getBooksForSellAsync(int limit) {
            MLVApplication.LibService.getBooksForSellRequest inValue = new MLVApplication.LibService.getBooksForSellRequest();
            inValue.limit = limit;
            return ((MLVApplication.LibService.MLVLibService)(this)).getBooksForSellAsync(inValue);
        }
        
        public int getTotalBooks() {
            return base.Channel.getTotalBooks();
        }
        
        public System.Threading.Tasks.Task<int> getTotalBooksAsync() {
            return base.Channel.getTotalBooksAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.searchBooksResponse MLVApplication.LibService.MLVLibService.searchBooks(MLVApplication.LibService.searchBooksRequest request) {
            return base.Channel.searchBooks(request);
        }
        
        public MLVApplication.LibService.BookPOJO[] searchBooks(string[] tags) {
            MLVApplication.LibService.searchBooksRequest inValue = new MLVApplication.LibService.searchBooksRequest();
            inValue.tags = tags;
            MLVApplication.LibService.searchBooksResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).searchBooks(inValue);
            return retVal.searchBooksReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.searchBooksResponse> MLVApplication.LibService.MLVLibService.searchBooksAsync(MLVApplication.LibService.searchBooksRequest request) {
            return base.Channel.searchBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.searchBooksResponse> searchBooksAsync(string[] tags) {
            MLVApplication.LibService.searchBooksRequest inValue = new MLVApplication.LibService.searchBooksRequest();
            inValue.tags = tags;
            return ((MLVApplication.LibService.MLVLibService)(this)).searchBooksAsync(inValue);
        }
        
        public bool sellBook(long cardID, string secret, string devise, double price) {
            return base.Channel.sellBook(cardID, secret, devise, price);
        }
        
        public System.Threading.Tasks.Task<bool> sellBookAsync(long cardID, string secret, string devise, double price) {
            return base.Channel.sellBookAsync(cardID, secret, devise, price);
        }
        
        public MLVApplication.LibService.BookPOJO getMostConsultedBook(int number) {
            return base.Channel.getMostConsultedBook(number);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.BookPOJO> getMostConsultedBookAsync(int number) {
            return base.Channel.getMostConsultedBookAsync(number);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getMostConsultedBookFormattedResponse MLVApplication.LibService.MLVLibService.getMostConsultedBookFormatted(MLVApplication.LibService.getMostConsultedBookFormattedRequest request) {
            return base.Channel.getMostConsultedBookFormatted(request);
        }
        
        public string[] getMostConsultedBookFormatted(int number) {
            MLVApplication.LibService.getMostConsultedBookFormattedRequest inValue = new MLVApplication.LibService.getMostConsultedBookFormattedRequest();
            inValue.number = number;
            MLVApplication.LibService.getMostConsultedBookFormattedResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getMostConsultedBookFormatted(inValue);
            return retVal.getMostConsultedBookFormattedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getMostConsultedBookFormattedResponse> MLVApplication.LibService.MLVLibService.getMostConsultedBookFormattedAsync(MLVApplication.LibService.getMostConsultedBookFormattedRequest request) {
            return base.Channel.getMostConsultedBookFormattedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getMostConsultedBookFormattedResponse> getMostConsultedBookFormattedAsync(int number) {
            MLVApplication.LibService.getMostConsultedBookFormattedRequest inValue = new MLVApplication.LibService.getMostConsultedBookFormattedRequest();
            inValue.number = number;
            return ((MLVApplication.LibService.MLVLibService)(this)).getMostConsultedBookFormattedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getMostSimilarBookResponse MLVApplication.LibService.MLVLibService.getMostSimilarBook(MLVApplication.LibService.getMostSimilarBookRequest request) {
            return base.Channel.getMostSimilarBook(request);
        }
        
        public MLVApplication.LibService.BookPOJO[] getMostSimilarBook(MLVApplication.LibService.BookPOJO model, int number) {
            MLVApplication.LibService.getMostSimilarBookRequest inValue = new MLVApplication.LibService.getMostSimilarBookRequest();
            inValue.model = model;
            inValue.number = number;
            MLVApplication.LibService.getMostSimilarBookResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getMostSimilarBook(inValue);
            return retVal.getMostSimilarBookReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getMostSimilarBookResponse> MLVApplication.LibService.MLVLibService.getMostSimilarBookAsync(MLVApplication.LibService.getMostSimilarBookRequest request) {
            return base.Channel.getMostSimilarBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getMostSimilarBookResponse> getMostSimilarBookAsync(MLVApplication.LibService.BookPOJO model, int number) {
            MLVApplication.LibService.getMostSimilarBookRequest inValue = new MLVApplication.LibService.getMostSimilarBookRequest();
            inValue.model = model;
            inValue.number = number;
            return ((MLVApplication.LibService.MLVLibService)(this)).getMostSimilarBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.searchFormattedBooksResponse MLVApplication.LibService.MLVLibService.searchFormattedBooks(MLVApplication.LibService.searchFormattedBooksRequest request) {
            return base.Channel.searchFormattedBooks(request);
        }
        
        public string[] searchFormattedBooks(string[] tags) {
            MLVApplication.LibService.searchFormattedBooksRequest inValue = new MLVApplication.LibService.searchFormattedBooksRequest();
            inValue.tags = tags;
            MLVApplication.LibService.searchFormattedBooksResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).searchFormattedBooks(inValue);
            return retVal.searchFormattedBooksReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.searchFormattedBooksResponse> MLVApplication.LibService.MLVLibService.searchFormattedBooksAsync(MLVApplication.LibService.searchFormattedBooksRequest request) {
            return base.Channel.searchFormattedBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.searchFormattedBooksResponse> searchFormattedBooksAsync(string[] tags) {
            MLVApplication.LibService.searchFormattedBooksRequest inValue = new MLVApplication.LibService.searchFormattedBooksRequest();
            inValue.tags = tags;
            return ((MLVApplication.LibService.MLVLibService)(this)).searchFormattedBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getBookFromCategoryResponse MLVApplication.LibService.MLVLibService.getBookFromCategory(MLVApplication.LibService.getBookFromCategoryRequest request) {
            return base.Channel.getBookFromCategory(request);
        }
        
        public MLVApplication.LibService.BookPOJO[] getBookFromCategory(string category) {
            MLVApplication.LibService.getBookFromCategoryRequest inValue = new MLVApplication.LibService.getBookFromCategoryRequest();
            inValue.category = category;
            MLVApplication.LibService.getBookFromCategoryResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getBookFromCategory(inValue);
            return retVal.getBookFromCategoryReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getBookFromCategoryResponse> MLVApplication.LibService.MLVLibService.getBookFromCategoryAsync(MLVApplication.LibService.getBookFromCategoryRequest request) {
            return base.Channel.getBookFromCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getBookFromCategoryResponse> getBookFromCategoryAsync(string category) {
            MLVApplication.LibService.getBookFromCategoryRequest inValue = new MLVApplication.LibService.getBookFromCategoryRequest();
            inValue.category = category;
            return ((MLVApplication.LibService.MLVLibService)(this)).getBookFromCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getFormattedBookFromCategoryResponse MLVApplication.LibService.MLVLibService.getFormattedBookFromCategory(MLVApplication.LibService.getFormattedBookFromCategoryRequest request) {
            return base.Channel.getFormattedBookFromCategory(request);
        }
        
        public string[] getFormattedBookFromCategory(string category) {
            MLVApplication.LibService.getFormattedBookFromCategoryRequest inValue = new MLVApplication.LibService.getFormattedBookFromCategoryRequest();
            inValue.category = category;
            MLVApplication.LibService.getFormattedBookFromCategoryResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getFormattedBookFromCategory(inValue);
            return retVal.getFormattedBookFromCategoryReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedBookFromCategoryResponse> MLVApplication.LibService.MLVLibService.getFormattedBookFromCategoryAsync(MLVApplication.LibService.getFormattedBookFromCategoryRequest request) {
            return base.Channel.getFormattedBookFromCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedBookFromCategoryResponse> getFormattedBookFromCategoryAsync(string category) {
            MLVApplication.LibService.getFormattedBookFromCategoryRequest inValue = new MLVApplication.LibService.getFormattedBookFromCategoryRequest();
            inValue.category = category;
            return ((MLVApplication.LibService.MLVLibService)(this)).getFormattedBookFromCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getFormattedBooksResponse MLVApplication.LibService.MLVLibService.getFormattedBooks(MLVApplication.LibService.getFormattedBooksRequest request) {
            return base.Channel.getFormattedBooks(request);
        }
        
        public string[] getFormattedBooks(int limit) {
            MLVApplication.LibService.getFormattedBooksRequest inValue = new MLVApplication.LibService.getFormattedBooksRequest();
            inValue.limit = limit;
            MLVApplication.LibService.getFormattedBooksResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getFormattedBooks(inValue);
            return retVal.getFormattedBooksReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedBooksResponse> MLVApplication.LibService.MLVLibService.getFormattedBooksAsync(MLVApplication.LibService.getFormattedBooksRequest request) {
            return base.Channel.getFormattedBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedBooksResponse> getFormattedBooksAsync(int limit) {
            MLVApplication.LibService.getFormattedBooksRequest inValue = new MLVApplication.LibService.getFormattedBooksRequest();
            inValue.limit = limit;
            return ((MLVApplication.LibService.MLVLibService)(this)).getFormattedBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.LibService.getFormattedRangeResponse MLVApplication.LibService.MLVLibService.getFormattedRange(MLVApplication.LibService.getFormattedRangeRequest request) {
            return base.Channel.getFormattedRange(request);
        }
        
        public string[] getFormattedRange(int offset, int limit) {
            MLVApplication.LibService.getFormattedRangeRequest inValue = new MLVApplication.LibService.getFormattedRangeRequest();
            inValue.offset = offset;
            inValue.limit = limit;
            MLVApplication.LibService.getFormattedRangeResponse retVal = ((MLVApplication.LibService.MLVLibService)(this)).getFormattedRange(inValue);
            return retVal.getFormattedRangeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedRangeResponse> MLVApplication.LibService.MLVLibService.getFormattedRangeAsync(MLVApplication.LibService.getFormattedRangeRequest request) {
            return base.Channel.getFormattedRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.LibService.getFormattedRangeResponse> getFormattedRangeAsync(int offset, int limit) {
            MLVApplication.LibService.getFormattedRangeRequest inValue = new MLVApplication.LibService.getFormattedRangeRequest();
            inValue.offset = offset;
            inValue.limit = limit;
            return ((MLVApplication.LibService.MLVLibService)(this)).getFormattedRangeAsync(inValue);
        }
    }
}
