//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLVApplication.SellingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://selling.bilmancamp.rmirest.upem.fr", ConfigurationName="SellingService.SellingService")]
    public interface SellingService {
        
        // CODEGEN: Generating message contract since element name currencyFrom from namespace http://selling.bilmancamp.rmirest.upem.fr is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MLVApplication.SellingService.changeResponse change(MLVApplication.SellingService.changeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.SellingService.changeResponse> changeAsync(MLVApplication.SellingService.changeRequest request);
        
        // CODEGEN: Generating message contract since element name password from namespace http://selling.bilmancamp.rmirest.upem.fr is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MLVApplication.SellingService.sellBookResponse sellBook(MLVApplication.SellingService.sellBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MLVApplication.SellingService.sellBookResponse> sellBookAsync(MLVApplication.SellingService.sellBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="change", Namespace="http://selling.bilmancamp.rmirest.upem.fr", Order=0)]
        public MLVApplication.SellingService.changeRequestBody Body;
        
        public changeRequest() {
        }
        
        public changeRequest(MLVApplication.SellingService.changeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://selling.bilmancamp.rmirest.upem.fr")]
    public partial class changeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string currencyFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currencyTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double amount;
        
        public changeRequestBody() {
        }
        
        public changeRequestBody(string currencyFrom, string currencyTo, double amount) {
            this.currencyFrom = currencyFrom;
            this.currencyTo = currencyTo;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeResponse", Namespace="http://selling.bilmancamp.rmirest.upem.fr", Order=0)]
        public MLVApplication.SellingService.changeResponseBody Body;
        
        public changeResponse() {
        }
        
        public changeResponse(MLVApplication.SellingService.changeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://selling.bilmancamp.rmirest.upem.fr")]
    public partial class changeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double changeReturn;
        
        public changeResponseBody() {
        }
        
        public changeResponseBody(double changeReturn) {
            this.changeReturn = changeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sellBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sellBook", Namespace="http://selling.bilmancamp.rmirest.upem.fr", Order=0)]
        public MLVApplication.SellingService.sellBookRequestBody Body;
        
        public sellBookRequest() {
        }
        
        public sellBookRequest(MLVApplication.SellingService.sellBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://selling.bilmancamp.rmirest.upem.fr")]
    public partial class sellBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string currency;
        
        public sellBookRequestBody() {
        }
        
        public sellBookRequestBody(long id, string password, double price, string currency) {
            this.id = id;
            this.password = password;
            this.price = price;
            this.currency = currency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sellBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sellBookResponse", Namespace="http://selling.bilmancamp.rmirest.upem.fr", Order=0)]
        public MLVApplication.SellingService.sellBookResponseBody Body;
        
        public sellBookResponse() {
        }
        
        public sellBookResponse(MLVApplication.SellingService.sellBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://selling.bilmancamp.rmirest.upem.fr")]
    public partial class sellBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sellBookReturn;
        
        public sellBookResponseBody() {
        }
        
        public sellBookResponseBody(bool sellBookReturn) {
            this.sellBookReturn = sellBookReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellingServiceChannel : MLVApplication.SellingService.SellingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellingServiceClient : System.ServiceModel.ClientBase<MLVApplication.SellingService.SellingService>, MLVApplication.SellingService.SellingService {
        
        public SellingServiceClient() {
        }
        
        public SellingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.SellingService.changeResponse MLVApplication.SellingService.SellingService.change(MLVApplication.SellingService.changeRequest request) {
            return base.Channel.change(request);
        }
        
        public double change(string currencyFrom, string currencyTo, double amount) {
            MLVApplication.SellingService.changeRequest inValue = new MLVApplication.SellingService.changeRequest();
            inValue.Body = new MLVApplication.SellingService.changeRequestBody();
            inValue.Body.currencyFrom = currencyFrom;
            inValue.Body.currencyTo = currencyTo;
            inValue.Body.amount = amount;
            MLVApplication.SellingService.changeResponse retVal = ((MLVApplication.SellingService.SellingService)(this)).change(inValue);
            return retVal.Body.changeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.SellingService.changeResponse> MLVApplication.SellingService.SellingService.changeAsync(MLVApplication.SellingService.changeRequest request) {
            return base.Channel.changeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.SellingService.changeResponse> changeAsync(string currencyFrom, string currencyTo, double amount) {
            MLVApplication.SellingService.changeRequest inValue = new MLVApplication.SellingService.changeRequest();
            inValue.Body = new MLVApplication.SellingService.changeRequestBody();
            inValue.Body.currencyFrom = currencyFrom;
            inValue.Body.currencyTo = currencyTo;
            inValue.Body.amount = amount;
            return ((MLVApplication.SellingService.SellingService)(this)).changeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MLVApplication.SellingService.sellBookResponse MLVApplication.SellingService.SellingService.sellBook(MLVApplication.SellingService.sellBookRequest request) {
            return base.Channel.sellBook(request);
        }
        
        public bool sellBook(long id, string password, double price, string currency) {
            MLVApplication.SellingService.sellBookRequest inValue = new MLVApplication.SellingService.sellBookRequest();
            inValue.Body = new MLVApplication.SellingService.sellBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            inValue.Body.price = price;
            inValue.Body.currency = currency;
            MLVApplication.SellingService.sellBookResponse retVal = ((MLVApplication.SellingService.SellingService)(this)).sellBook(inValue);
            return retVal.Body.sellBookReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MLVApplication.SellingService.sellBookResponse> MLVApplication.SellingService.SellingService.sellBookAsync(MLVApplication.SellingService.sellBookRequest request) {
            return base.Channel.sellBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<MLVApplication.SellingService.sellBookResponse> sellBookAsync(long id, string password, double price, string currency) {
            MLVApplication.SellingService.sellBookRequest inValue = new MLVApplication.SellingService.sellBookRequest();
            inValue.Body = new MLVApplication.SellingService.sellBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.password = password;
            inValue.Body.price = price;
            inValue.Body.currency = currency;
            return ((MLVApplication.SellingService.SellingService)(this)).sellBookAsync(inValue);
        }
    }
}
